<?xml version="1.0" ?>
<robot 
     xmlns:xacro="http://www.ros.org/wiki/xacro"
     name="abby">
   <xacro:property name="track" value=".56515" />
   <xacro:property name="tirediam" value="0.3302" />
   <xacro:include filename="$(find abby_description)/urdf/irb120.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find abby_description)/urdf/materials.xacro" />  
   <!--'$(find abby_description)/urdf/irb120.xacro' -->
   
   
	<link name="base_link">
		<!--visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/al_frame_iam_3826baa4.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.0446356739978 0.177065647653 -0.0893087163603"/>
			<material name="frame1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual-->
		<!--inertial>
			<mass value="0.01"/>
			<inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</inertial-->
	</link>
		<joint name="base_to_frame1" type="fixed">
		<parent link="base_link"/>
		<child link="frame1"/>
		<!-- z = -0.065 puts x axis right through drive-wheel axle-->
        <!-- z = 0.105 puts base_link at floor level -->
        <!-- y = -0.05 to center? 0.26 aligned right side, -0.35 aligned left side, so ctr ~-0.045 -->		
		<origin rpy="0 0 1.5708" xyz="-0.06 -0.045  0.105"/>
	</joint>
	<link name="frame1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/al_frame_iam_3826baa4.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.0446356739978 0.177065647653 -0.0893087163603"/>
			<material name="frame1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="12.7774249075"/>
			<inertia ixx="2.11995607184" ixy="-0.0128393605839" ixz="-0.0068818565379" iyy="1.84586933127" iyz="0.34872380742" izz="1.11710077832"/>
			<origin rpy="0 0 0" xyz="0.0382793240557 -0.271251963735 0.649589084908"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/al_frame_iam_3826baa4.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.0446356739978 0.177065647653 -0.0893087163603"/>
		</collision-->
	</link>
	<link name="f_r_frame_bracket1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0946635865578 -0.0205552039632 -0.424782665556"/>
			<material name="f_r_frame_bracket1_color">
				<color rgba="0.639216 0.639216 0.639216 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.71440798275"/>
			<inertia ixx="0.00043051877529" ixy="0.0" ixz="-1.18150140291e-05" iyy="0.00109167940213" iyz="0.0" izz="0.00105983757016"/>
			<origin rpy="0 0 0" xyz="-0.0175668955453 0.00484479603152 -0.408054413923"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0946635865578 -0.0205552039632 -0.424782665556"/>
		</collision-->
	</link>
	<joint name="frame--f_r_frame_bracket1" type="fixed">
		<parent link="frame1"/>
		<child link="f_r_frame_bracket1"/>
		<origin rpy="0 -0.0938814541614 1.5707963268" xyz="-0.197196963951 -0.46840807491 0.660027160644"/>
	</joint>
	<link name="f_l_frame_bracket1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.050800692836 -0.0508000000121 -0.00634958439213"/>
			<material name="f_l_frame_bracket1_color">
				<color rgba="0.639216 0.639216 0.639216 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.71440798275"/>
			<inertia ixx="0.00043051877529" ixy="0.0" ixz="-1.18150140291e-05" iyy="0.00109167940213" iyz="0.0" izz="0.00105983757016"/>
			<origin rpy="0 0 0" xyz="0.026295998169 -0.025399999994 0.0103786672398"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.050800692836 -0.0508000000121 -0.00634958439213"/>
		</collision-->
	</link>
	<joint name="f_l_frame_bracket--f_r_frame_bracket1" type="fixed">
		<parent link="f_r_frame_bracket1"/>
		<child link="f_l_frame_bracket1"/>
		<origin rpy="0 0 0" xyz="-0.0438628937327 -0.464082383966 -0.418433081198"/>
	</joint>
	<link name="f_l_frame_plate1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/front frame plate_ipt_3e5bfe16.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="f_l_frame_plate1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.072583397455"/>
			<inertia ixx="0.000139975007751" ixy="0.0" ixz="0.0" iyy="3.5475798236e-05" iyz="0.0" izz="0.000174962980108"/>
			<origin rpy="0 0 0" xyz="0.0380034800186 0.0762017426097 0.00317605933453"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/front frame plate_ipt_3e5bfe16.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision-->
	</link>
	<joint name="f_l_frame_plate--f_l_frame_bracket1" type="fixed">
		<parent link="f_l_frame_bracket1"/>
		<child link="f_l_frame_plate1"/>
		<origin rpy="-3.14159265359 0 1.57079632679" xyz="-0.050800692836 -0.0508000000121 -0.00634958439213"/>
	</joint>
	<link name="f_r_frame_plate1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/front frame plate_ipt_3e5bfe16.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0381000000045 -0.0762009322898 -0.00634941359797"/>
			<material name="f_r_frame_plate1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.072583397455"/>
			<inertia ixx="0.000139975007751" ixy="0.0" ixz="0.0" iyy="3.5475798236e-05" iyz="0.0" izz="0.000174962980108"/>
			<origin rpy="0 0 0" xyz="-9.52500002381e-05 9.97890829302e-07 -0.00317559036918"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/front frame plate_ipt_3e5bfe16.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0381000000045 -0.0762009322898 -0.00634941359797"/>
		</collision-->
	</link>
	<joint name="f_r_frame_plate--f_r_frame_bracket1" type="fixed">
		<parent link="f_r_frame_bracket1"/>
		<child link="f_r_frame_plate1"/>
		<origin rpy="0 0 -1.57079632679" xyz="-0.0184628418291 -0.00785520396718 -0.424783134521"/>
	</joint>
	<link name="b_r_frame_bracket1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/short frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0774480173821 -0.0263550400145 -0.00822489041407"/>
			<material name="b_r_frame_bracket1_color">
				<color rgba="0.639216 0.639216 0.639216 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.71440798275"/>
			<inertia ixx="0.00044432538895" ixy="0.0" ixz="-8.3387205787e-05" iyy="0.00086832128551" iyz="0.0" izz="0.00083243813657"/>
			<origin rpy="0 0 0" xyz="-0.00691246125573 -0.000955040002614 0.00995368760594"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/short frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0774480173821 -0.0263550400145 -0.00822489041407"/>
		</collision-->
	</link>
	<joint name="frame--b_r_frame_bracket1" type="fixed">
		<parent link="frame1"/>
		<child link="b_r_frame_bracket1"/>
		<origin rpy="0 -0.0938814541614 1.57079632654" xyz="-0.202996799965 0.113567247403 0.29642350598"/>
	</joint>
	<link name="b_r_frame_plate1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/back frame plate_ipt_475e4947.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0254000000255 -0.126998971214 1.58112569598e-06"/>
			<material name="b_r_frame_plate1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.0971640215777"/>
			<inertia ixx="0.0003344255636" ixy="8.4155085275e-07" ixz="0.0" iyy="4.7517225512e-05" iyz="0.0" izz="0.00038129137915"/>
			<origin rpy="0 0 0" xyz="0.0126431039946 -0.025550836608 0.00317565745359"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/back frame plate_ipt_475e4947.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0254000000255 -0.126998971214 1.58112569598e-06"/>
		</collision-->
	</link>
	<joint name="b_r_frame_plate--b_r_frame_bracket1" type="fixed">
		<parent link="b_r_frame_bracket1"/>
		<child link="b_r_frame_plate1"/>
		<origin rpy="3.14159265359 0 -1.57079632679" xyz="-0.0520471238425 -0.000955040009423 -0.00822349691669"/>
	</joint>
	<link name="IRC5_Compact1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/irc5_compact_ipt_c844072c.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.000849884100615 0.0283509919265 -0.462400284136"/>
			<material name="IRC5_Compact1_color">
				<color rgba="0.498039 0.498039 0.498039 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="28.440241599"/>
			<inertia ixx="0.75499468089" ixy="-0.00122306756239" ixz="-0.00124304296401" iyy="1.08063235538" iyz="-0.0064925615368" izz="0.61093241216"/>
			<origin rpy="0 0 0" xyz="-0.225686620068 0.151686511222 -0.249482492333"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/irc5_compact_ipt_c844072c.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.000849884100615 0.0283509919265 -0.462400284136"/>
		</collision-->
	</link>
	<joint name="frame--IRC5_Compact1" type="fixed">
		<parent link="frame1"/>
		<child link="IRC5_Compact1"/>
		<origin rpy="1.5707959092 0 3.14159265334" xyz="-0.18299683996 0.0935673788127 0.353829950251"/>
	</joint>
	<link name="router1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/router keepout_ipt_2b3ba7b4.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.0783000719655 0.725341498268 -1.11194969221e-06"/>
			<material name="router1_color">
				<color rgba="0.25098 0.321569 0.392157 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.28349523125"/>
			<inertia ixx="0.00067729370465" ixy="0.0" ixz="0.0" iyy="0.0008954399563" iyz="0.0" izz="0.00150414540089"/>
			<origin rpy="0 0 0" xyz="0.0783000719663 0.727175853591 0.0190494073449"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/router keepout_ipt_2b3ba7b4.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.0783000719655 0.725341498268 -1.11194969221e-06"/>
		</collision-->
	</link>
	<joint name="frame--router1" type="fixed">
		<parent link="frame1"/>
		<child link="router1"/>
		<origin rpy="-1.5707959092 0 0" xyz="-0.0354469698523 -0.430316747951 1.61002981286"/>
	</joint>
	<link name="SICK_LMS2911">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/lms291_ipt_2ad4e53c.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0683999139953 -0.00245779587475 -0.0929987962566"/>
			<material name="SICK_LMS2911_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="3.71737544502"/>
			<inertia ixx="0.0174805834039" ixy="-4.4195210288e-07" ixz="4.1599227461e-07" iyy="0.0127643577208" iyz="0.00072853444335" izz="0.0175041992098"/>
			<origin rpy="0 0 0" xyz="-0.0684016920036 0.0653465146418 -0.0708751847642"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/sick lms291_ipt_2ad4e53c.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0683999139953 -0.00245779587475 -0.0929987962566"/>
		</collision-->
	</link>

	<joint name="frame--SICK_LMS2911" type="fixed">
            <!-- 
      		<axis xyz="0 1 0" />
      		<origin xyz="0.1 0 0.56" rpy="0 0 0"/>
            -->
		<parent link="frame1"/>
		<child link="SICK_LMS2911"/>
		<origin rpy="1.5707959092 0 -3.14159265358" xyz="-0.0255468119868 -0.474758386705 0.311455920061"/>
	</joint>

 <gazebo reference="SICK_LMS2911">
    <sensor type="gpu_ray" name="sick_lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>181</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>80.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_gpu_laser.so">
       <!-- <topicName>/laser/scan</topicName> --> 
                <topicName>/scan</topicName>
        <frameName>SICK_LMS2911</frameName>
      </plugin>
    </sensor>
  </gazebo>

	<link name="base_plate1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/base plate_iam_348b8023.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.296284250178 -0.709693779926 -0.581261979343"/>
			<material name="base_plate1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="11.253309185"/>
			<inertia ixx="0.192702049774" ixy="-0.0128927375727" ixz="-0.00057983680454" iyy="0.235790506928" iyz="0.002976996201" izz="0.41200655867"/>
			<origin rpy="0 0 0" xyz="-0.259429264405 -0.197794168785 -0.0311541484255"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/base plate_iam_348b8023.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.296284250178 -0.709693779926 -0.581261979343"/>
		</collision-->
	</link>
	<joint name="frame--base_plate1" type="fixed">
		<parent link="frame1"/>
		<child link="base_plate1"/>
		<origin rpy="0 0 1.5707963268" xyz="-0.182996839959 0.0950674391444 0.365829741316"/>
	</joint>
	<link name="top_plate1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/top plate_ipt_9041f1eb.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.039999919998 -0.0370003177082 -0.00635046315153"/>
			<material name="top_plate1_color">
				<color rgba="0.2 0.2 0.2 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="2.41906254029"/>
			<inertia ixx="0.070476646621" ixy="-3.2774173452e-05" ixz="0.0" iyy="0.05993791034" iyz="0.0" izz="0.130398461926"/>
			<origin rpy="0 0 0" xyz="0.229580439988 0.257942378411 -0.00317445298106"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/top plate_ipt_9041f1eb.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.039999919998 -0.0370003177082 -0.00635046315153"/>
		</collision-->
	</link>
	<joint name="frame--top_plate1" type="fixed">
		<parent link="frame1"/>
		<child link="top_plate1"/>
		<origin rpy="-3.14159265359 0 0" xyz="-0.182996839929 0.0965675138916 0.656087848989"/>
	</joint>
	<link name="main_breaker1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/breaker_iam_746c8f85.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0160837880011 -0.0289106364367 0.00508056290676"/>
			<material name="main_breaker1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.0936536702263"/>
			<inertia ixx="3.6925814571e-05" ixy="-4.3535021216e-06" ixz="1.05382973255e-07" iyy="2.44166070505e-05" iyz="-2.55254379072e-12" izz="4.8649438065e-05"/>
			<origin rpy="0 0 0" xyz="-0.0161287460005 -0.0289109627394 0.0153385723229"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/breaker_iam_746c8f85.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0160837880011 -0.0289106364367 0.00508056290676"/>
		</collision-->
	</link>
	<joint name="main_breaker--top_plate1" type="fixed">
		<parent link="top_plate1"/>
		<child link="main_breaker1"/>
		<origin rpy="3.14159265359 0 0" xyz="0.426298867993 0.159767684312 -0.00635046455001"/>
	</joint>
	<link name="compressor1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/compressor_iam_e870b89.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.217095026073 0.0541649919903 0.058507418554"/>
			<material name="compressor1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="2.12621423437"/>
			<inertia ixx="-0.0061140063136" ixy="0.0073422915937" ixz="0.0121866630191" iyy="-0.0247184035886" iyz="0.0043080263318" izz="-0.0223276763534"/>
			<origin rpy="0 0 0" xyz="0.0555649192101 -0.000189230004887 -0.0360164073274"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/compressor_iam_e870b89.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.217095026073 0.0541649919903 0.058507418554"/>
		</collision-->
	</link>
	<joint name="compressor--top_plate1" type="fixed">
		<parent link="top_plate1"/>
		<child link="compressor1"/>
		<origin rpy="2.35090778551e-05 1.5707959092 1.57081983614" xyz="0.40450007998 0.426550996313 -0.00635023492284"/>
	</joint>
	<link name="PC1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/pc_ipt_a7ade237.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 -0.095249567657 -1.9383533062e-07"/>
			<material name="PC1_color">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="13.0796535036"/>
			<inertia ixx="0.199045542023" ixy="0.000104306361732" ixz="0.00061701926176" iyy="0.3078833877" iyz="0.000148148651798" izz="0.128774326576"/>
			<origin rpy="0 0 0" xyz="0.164833477815 -0.0476494270341 0.207873207523"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/pc_ipt_a7ade237.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 -0.095249567657 -1.9383533062e-07"/>
		</collision-->
	</link>
	<joint name="PC--top_plate1" type="fixed">
		<parent link="top_plate1"/>
		<child link="PC1"/>
		<origin rpy="1.57079674439 0 0" xyz="0.0108000799797 0.436074033464 -0.00635125529283"/>
	</joint>
	<link name="spike_relay1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/spike h_iam_f19c9874.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.165495388905 -0.231988605905 -4.80033572003e-07"/>
			<material name="spike_relay1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.02553552678"/>
			<inertia ixx="4.8431130863e-06" ixy="-7.8309953837e-09" ixz="-2.27668366993e-09" iyy="8.2511635883e-06" iyz="-1.99978761416e-07" izz="1.02136458377e-05"/>
			<origin rpy="0 0 0" xyz="0.16538182583 -0.230617385381 0.00965819617544"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/spike h_iam_f19c9874.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.165495388905 -0.231988605905 -4.80033572003e-07"/>
		</collision-->
	</link>
	<joint name="top_plate--spike_relay1" type="fixed">
		<parent link="top_plate1"/>
		<child link="spike_relay1"/>
		<origin rpy="3.14159264636 0 0.00520380555278" xyz="0.229875079988 0.264625478066 -0.00635030519039"/>
	</joint>
	<link name="b_l_frame_bracket1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/short frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0635428211507 -0.00444500001769 -0.0603982600527"/>
			<material name="b_l_frame_bracket1_color">
				<color rgba="0.639216 0.639216 0.639216 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.71440798275"/>
			<inertia ixx="0.00044432538895" ixy="0.0" ixz="-8.3387205787e-05" iyy="0.00086832128551" iyz="0.0" izz="0.00083243813657"/>
			<origin rpy="0 0 0" xyz="0.00699273497077 0.020955000008 -0.0422196820327"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/short frame bracket_ipt_f5a4f28d.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.0635428211507 -0.00444500001769 -0.0603982600527"/>
		</collision-->
	</link>
	<joint name="b_l_frame_bracket--frame1" type="fixed">
		<parent link="frame1"/>
		<child link="b_l_frame_bracket1"/>
		<origin rpy="0 -0.0938814541614 1.57079632635" xyz="0.313240420039 0.0948323645811 0.347063600205"/>
	</joint>
	<link name="b_l_frame_plate1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/back frame plate_ipt_475e4947.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="b_l_frame_plate1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.0971640215777"/>
			<inertia ixx="0.0003344255636" ixy="8.4155085275e-07" ixz="0.0" iyy="4.7517225512e-05" iyz="0.0" izz="0.00038129137915"/>
			<origin rpy="0 0 0" xyz="0.0380441199796 0.101448124476 0.00317600333501"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/back frame plate_ipt_475e4947.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision-->
	</link>
	<joint name="b_l_frame_plate--b_l_frame_bracket1" type="fixed">
		<parent link="b_l_frame_bracket1"/>
		<child link="b_l_frame_plate1"/>
		<origin rpy="0 0 1.57079632699" xyz="0.0888570334677 -0.00444499995661 -0.0667485273456"/>
	</joint>
	<link name="frame_solid:11">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/frame_solid_iam_8d469021.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-3.47155770013 -0.38147033036 2.30808809655"/>
			<material name="frame_solid:11_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="76.9265443978"/>
			<inertia ixx="-0.199581653007" ixy="-0.082679316884" ixz="0.0112391336768" iyy="2.03829571699" iyz="-0.249221082043" izz="-0.62699233072"/>
			<origin rpy="0 0 0" xyz="-0.250028710016 -0.128949655059 0.228101121891"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/frame_solid_iam_8d469021.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-3.47155770013 -0.38147033036 2.30808809655"/>
		</collision-->
	</link>
	<joint name="b_l_frame_plate--frame_solid:11" type="fixed">
		<parent link="b_l_frame_plate1"/>
		<child link="frame_solid:11"/>
		<origin rpy="1.47691420527 0 -3.14159265334" xyz="0.0380441199796 0.101448124476 0.00317600333501"/>
	</joint>
	<link name="l_caster1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster_ipt_ca03a3d7.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="8.42753967015e-07 -0.13652463702 -0.0253998728835"/>
			<material name="l_caster1_color">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.141176996424"/>
			<inertia ixx="0.00051323847608" ixy="0.0" ixz="0.0" iyy="0.00026112292147" iyz="0.000151341028831" izz="0.00058482333902"/>
			<origin rpy="0 0 0" xyz="-2.95905491936e-07 -0.0595480601633 0.018131413861"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster_ipt_ca03a3d7.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="8.42753967015e-07 -0.13652463702 -0.0253998728835"/>
		</collision-->
	</link>
	<joint name="l_caster_joint" type="continuous">
		<parent link="frame_solid:11"/>
		<child link="l_caster1"/>
		<axis xyz="0 1 0"/>
		<origin rpy="3.14159154933 -0.529419117266 -3.1415922637" xyz="-0.016388080036 -0.149221796489 0.625818601504"/>
	</joint>
	<link name="l_caster_wheel1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster wheel_ipt_4784d7d8.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-1.18418908775e-06 -0.0380989161968 -1.67691861175e-06"/>
			<material name="l_caster_wheel1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="1.4177347039"/>
			<inertia ixx="0.0034966317219" ixy="0.0" ixz="0.0" iyy="0.0063467697834" iyz="0.0" izz="0.0034966317219"/>
			<origin rpy="0 0 0" xyz="-1.18418908775e-06 -0.0380989161968 -1.67691861175e-06"/>
		</inertial>
		<collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster wheel_ipt_4784d7d8.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-1.18418908775e-06 -0.0380989161968 -1.67691861175e-06"/>
		</collision>
	</link>
	<joint name="l_caster_wheel_joint" type="continuous">
		<parent link="l_caster1"/>
		<child link="l_caster_wheel1"/>
		<axis xyz="0 1 0"/>
		<origin rpy="6.29554520079e-07 -0.0978245101151 -1.57079646214" xyz="0.0374386651859 -0.136525432368 0.0571509283666"/>
	</joint>
	<link name="r_caster1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster_ipt_ca03a3d7.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-1.44488080778e-07 -0.136524926369 -0.0254000128924"/>
			<material name="r_caster1_color">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="0.141176996424"/>
			<inertia ixx="0.00051323847608" ixy="0.0" ixz="0.0" iyy="0.00026112292147" iyz="0.000151341028831" izz="0.00058482333902"/>
			<origin rpy="0 0 0" xyz="1.20291708094e-07 -0.0595479590544 0.0181329136137"/>
		</inertial>
		<!--collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster_ipt_ca03a3d7.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-1.44488080778e-07 -0.136524926369 -0.0254000128924"/>
		</collision-->
	</link>
	<joint name="r_caster_joint" type="continuous">
		<parent link="frame_solid:11"/>
		<child link="r_caster1"/>
		<axis xyz="0 1 0"/>
		<origin rpy="0 -0.0645005439914 0" xyz="-0.446765426036 -0.149221796474 0.625818601482"/>
	</joint>
	<link name="r_caster_wheel1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster wheel_ipt_4784d7d8.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-1.43565576272e-06 -0.0380999206774 0"/>
			<material name="r_caster_wheel1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="1.4177347039"/>
			<inertia ixx="0.0034966317219" ixy="0.0" ixz="0.0" iyy="0.0063467697834" iyz="0.0" izz="0.0034966317219"/>
			<origin rpy="0 0 0" xyz="-1.43565576272e-06 -0.0380999206774 0"/>
		</inertial>
		<collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/caster wheel_ipt_4784d7d8.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-1.43565576272e-06 -0.0380999206774 0"/>
		</collision>
	</link>
	<joint name="r_caster_wheel_joint" type="continuous">
		<parent link="r_caster1"/>
		<child link="r_caster_wheel1"/>
		<axis xyz="0 1 0"/>
		<origin rpy="-2.44191411285e-07 0.632428512243 -1.570796684" xyz="0.0374395826544 -0.13652471423 0.0571493788518"/>
	</joint>
	<link name="l_drive_wheel1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/wheel_ipt_982fa4fe.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="l_drive_wheel1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="3.52668067675"/>
			<inertia ixx="0.032456077033" ixy="0.0" ixz="0.0" iyy="0.062503458919" iyz="0.0" izz="0.032456077033"/>
			<origin rpy="0 0 0" xyz="0 -0.00071882 0"/>
		</inertial>
		<collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/wheel_ipt_982fa4fe.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
	</link>
	<joint name="l_drive_wheel_joint" type="continuous">
		<parent link="frame_solid:11"/>
		<child link="l_drive_wheel1"/>
		<axis xyz="0 -1 0"/>
		<origin rpy="0 -0.119809660819 1.57079632679" xyz="0.0466801199851 -0.217162738547 0.147715939724"/>
	</joint>
	<link name="r_drive_wheel1">
		<visual>
			<geometry>
				<mesh filename="package://abby_description/meshes/wheel_ipt_982fa4fe.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="r_drive wheel1_color">
				<color rgba="0.752941 0.752941 0.752941 1"/>
			</material>
		</visual>
		<inertial>
			<mass value="3.52668067675"/>
			<inertia ixx="0.032456077033" ixy="0.0" ixz="0.0" iyy="0.062503458919" iyz="0.0" izz="0.032456077033"/>
			<origin rpy="0 0 0" xyz="0 -0.000718058 0"/>
		</inertial>
		<collision>
			<geometry>
				<mesh filename="package://abby_description/meshes/wheel_ipt_982fa4fe.stl" scale="0.0254 0.0254 0.0254"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
	</link>
	<joint name="r_drive_wheel_joint" type="continuous">
		<parent link="frame_solid:11"/>
        <child link="r_drive_wheel1"/>
        <axis xyz="0 1 0"/>
		<origin rpy="0 -0.443332433305 -1.57079632679" xyz="-0.509833626015 -0.217162738527 0.147715939697"/>
	</joint>

 <!-- TRY ADDING a Kinect sensor: first the visual/collision/inertial box -->
    <link name="kinect_link">
      <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
              <!-- coarse model; a simple box -->
              <box size="0.05 0.2 0.05"/>
          </geometry>
      </collision>

      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
              <box size="0.05 0.2 0.05" />
          </geometry>
          <material name="kinect_gray">
              <color rgba="0.2 0.2 0.2 1.0"/>
          </material>
      </visual>

      <inertial>
          <mass value="0.1" />
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
      </inertial>
  </link>
  <!--the above displays a box meant to imply Kinect-->
  <!--now set the position/orientation of the above box: -->
  <joint name="kinect_joint" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="0.45 0 1.65" rpy="0 0.92 0"/>
      <parent link="base_link"/>
      <child link="kinect_link"/>
  </joint>


<gazebo>
  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <alwaysOn>true</alwaysOn>
    <updateRate>100</updateRate>
    <leftJoint>l_drive_wheel_joint</leftJoint>
    <rightJoint>r_drive_wheel_joint</rightJoint>
    <wheelSeparation>${track}</wheelSeparation>
    <wheelDiameter>${tirediam}</wheelDiameter>
    <torque>200</torque>
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <robotBaseFrame>base_link</robotBaseFrame>
  </plugin>
</gazebo> 	


  <joint name="fixed" type="fixed">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0.41 0 0.85" rpy="0 1.5708 0"/>    
  </joint>
  
 <link name="link1">
    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision-->

    <!--visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://abb_common/meshes/irb120/visual/base_link.stl"/>
      </geometry>
      <material name="abb_orange">
        <color rgba="1 0.43 0 1"/>
      </material>      
    </visua-->

    <visual>
      <!--origin xyz="0 0 ${height1/2}" rpy="0 0 0"/-->
       <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height1}"/-->
	       <mesh filename="package://abb_common/meshes/irb120/visual/base_link.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
    <limit effort="100" lower="-2.87979" upper="2.87979" velocity="4.36332"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height2}"/-->
	<mesh filename="package://abb_common/meshes/irb120/collision/link_1.stl"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin rpy="0 0 0" xyz="0 0 0.29"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" lower="-1.91986" upper="1.91986" velocity="4.36332"/>    
    <dynamics damping="1.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.2 0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	<mesh filename="package://abb_common/meshes/irb120/visual/link_2.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 -0.2" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <link name="link4">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.2 0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://abb_common/meshes/irb120/visual/link_3.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint3" type="continuous">
    <parent link="link3"/>
    <child link="link4"/>
    <origin rpy="0 0 0" xyz="0 0 0.27"/>
    <axis xyz="0 1 0"/>
   <limit effort="100" lower="-1.91986" upper="1.22173" velocity="4.36332"/>    
    <dynamics damping="1.7"/>
  </joint>  
 
   <link name="link5">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.2 0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://abb_common/meshes/irb120/visual/link_4.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint4" type="continuous">
    <parent link="link4"/>
    <child link="link5"/>
    <origin rpy="0 0 0" xyz="0 0 0.07"/>
    <axis xyz="1 0 0"/>
    <limit effort="20" lower="-2.79253" upper="2.79253" velocity="5.58505"/>    
    <dynamics damping="1.7"/>
  </joint>  
   
   <link name="link6">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.2 0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://abb_common/meshes/irb120/visual/link_5.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint5" type="continuous">
    <parent link="link5"/>
    <child link="link6"/>
   <origin rpy="0 0 0" xyz="0.302 0 0"/>
    <axis xyz="0 1 0"/>
     <limit effort="20" lower="-2.094395" upper="2.094395" velocity="5.58505"/>   
    <dynamics damping="1.7"/>
  </joint> 

   <link name="link7">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://abb_common/meshes/irb120/visual/link_6.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint6" type="continuous">
    <parent link="link6"/>
    <child link="link7"/>
    <origin rpy="0 0 0" xyz="0.072 0 0"/>
    <axis xyz="1 0 0"/>
     <limit effort="20" lower="-6.98132" upper="6.98132" velocity="7.33038"/>   
    <dynamics damping="0.7"/>
  </joint> 
    

 
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
    <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
    <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint5">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
    <transmission name="tran6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint6">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> 

<!-- SENSOR: have to add a static transform publication to fix calibration of point clouds; see launch file -->
<gazebo reference="kinect_link">
    <sensor type="depth" name="openni_camera_camera">       
        <always_on>1</always_on>
        <visualize>true</visualize>             
        <camera>
            <horizontal_fov>1.047</horizontal_fov>  
            <image>
                <width>640</width>
                <height>480</height>
                <format>R8G8B8</format>
            </image>
            <depth_camera>

            </depth_camera>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
            <alwaysOn>true</alwaysOn>
                <updateRate>10.0</updateRate>
                <cameraName>kinect</cameraName>
                <frameName>kinect_pc_frame</frameName>                   
            <imageTopicName>rgb/image_raw</imageTopicName>
            <depthImageTopicName>depth/image_raw</depthImageTopicName>
            <pointCloudTopicName>depth/points</pointCloudTopicName>
            <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>              
            <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>            
            <pointCloudCutoff>0.4</pointCloudCutoff>                
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            <CxPrime>0.0</CxPrime>
            <Cx>0.0</Cx>
            <Cy>0.0</Cy>
            <focalLength>0.0</focalLength>
            </plugin>
    </sensor>
</gazebo>


 
</robot>

