/* Auto-generated by genmsg_cpp for file /home/harlie/code/dev_stacks/navigation/navfn/srv/MakeNavPlan.srv */
#ifndef NAVFN_SERVICE_MAKENAVPLAN_H
#define NAVFN_SERVICE_MAKENAVPLAN_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"

#include "geometry_msgs/PoseStamped.h"
#include "geometry_msgs/PoseStamped.h"


#include "geometry_msgs/PoseStamped.h"

namespace navfn
{
template <class ContainerAllocator>
struct MakeNavPlanRequest_ : public ros::Message
{
  typedef MakeNavPlanRequest_<ContainerAllocator> Type;

  MakeNavPlanRequest_()
  : start()
  , goal()
  {
  }

  MakeNavPlanRequest_(const ContainerAllocator& _alloc)
  : start(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _start_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  start;

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  goal;


private:
  static const char* __s_getDataType_() { return "navfn/MakeNavPlanRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2fe3126bd5b2d56edd5005220333d4fd"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "8ffef29bc8b086289124c16a8daa989d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "geometry_msgs/PoseStamped start\n\
geometry_msgs/PoseStamped goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, start);
    ros::serialization::serialize(stream, goal);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, start);
    ros::serialization::deserialize(stream, goal);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(start);
    size += ros::serialization::serializationLength(goal);
    return size;
  }

  typedef boost::shared_ptr< ::navfn::MakeNavPlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navfn::MakeNavPlanRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct MakeNavPlanRequest
typedef  ::navfn::MakeNavPlanRequest_<std::allocator<void> > MakeNavPlanRequest;

typedef boost::shared_ptr< ::navfn::MakeNavPlanRequest> MakeNavPlanRequestPtr;
typedef boost::shared_ptr< ::navfn::MakeNavPlanRequest const> MakeNavPlanRequestConstPtr;


template <class ContainerAllocator>
struct MakeNavPlanResponse_ : public ros::Message
{
  typedef MakeNavPlanResponse_<ContainerAllocator> Type;

  MakeNavPlanResponse_()
  : plan_found(0)
  , error_message()
  , path()
  {
  }

  MakeNavPlanResponse_(const ContainerAllocator& _alloc)
  : plan_found(0)
  , error_message(_alloc)
  , path(_alloc)
  {
  }

  typedef uint8_t _plan_found_type;
  uint8_t plan_found;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_message_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  error_message;

  typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _path_type;
  std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  path;


  ROSCPP_DEPRECATED uint32_t get_path_size() const { return (uint32_t)path.size(); }
  ROSCPP_DEPRECATED void set_path_size(uint32_t size) { path.resize((size_t)size); }
  ROSCPP_DEPRECATED void get_path_vec(std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other > & vec) const { vec = this->path; }
  ROSCPP_DEPRECATED void set_path_vec(const std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other > & vec) { this->path = vec; }
private:
  static const char* __s_getDataType_() { return "navfn/MakeNavPlanResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8b8ed7edf1b237dc9ddda8c8ffed5d3a"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "8ffef29bc8b086289124c16a8daa989d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
uint8 plan_found\n\
string error_message\n\
\n\
\n\
geometry_msgs/PoseStamped[] path\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, plan_found);
    ros::serialization::serialize(stream, error_message);
    ros::serialization::serialize(stream, path);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, plan_found);
    ros::serialization::deserialize(stream, error_message);
    ros::serialization::deserialize(stream, path);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(plan_found);
    size += ros::serialization::serializationLength(error_message);
    size += ros::serialization::serializationLength(path);
    return size;
  }

  typedef boost::shared_ptr< ::navfn::MakeNavPlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navfn::MakeNavPlanResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct MakeNavPlanResponse
typedef  ::navfn::MakeNavPlanResponse_<std::allocator<void> > MakeNavPlanResponse;

typedef boost::shared_ptr< ::navfn::MakeNavPlanResponse> MakeNavPlanResponsePtr;
typedef boost::shared_ptr< ::navfn::MakeNavPlanResponse const> MakeNavPlanResponseConstPtr;

struct MakeNavPlan
{

typedef MakeNavPlanRequest Request;
typedef MakeNavPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct MakeNavPlan
} // namespace navfn

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::navfn::MakeNavPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2fe3126bd5b2d56edd5005220333d4fd";
  }

  static const char* value(const  ::navfn::MakeNavPlanRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2fe3126bd5b2d56eULL;
  static const uint64_t static_value2 = 0xdd5005220333d4fdULL;
};

template<class ContainerAllocator>
struct DataType< ::navfn::MakeNavPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "navfn/MakeNavPlanRequest";
  }

  static const char* value(const  ::navfn::MakeNavPlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::navfn::MakeNavPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PoseStamped start\n\
geometry_msgs/PoseStamped goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::navfn::MakeNavPlanRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::navfn::MakeNavPlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8b8ed7edf1b237dc9ddda8c8ffed5d3a";
  }

  static const char* value(const  ::navfn::MakeNavPlanResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8b8ed7edf1b237dcULL;
  static const uint64_t static_value2 = 0x9ddda8c8ffed5d3aULL;
};

template<class ContainerAllocator>
struct DataType< ::navfn::MakeNavPlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "navfn/MakeNavPlanResponse";
  }

  static const char* value(const  ::navfn::MakeNavPlanResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::navfn::MakeNavPlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
uint8 plan_found\n\
string error_message\n\
\n\
\n\
geometry_msgs/PoseStamped[] path\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::navfn::MakeNavPlanResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::navfn::MakeNavPlanRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.start);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MakeNavPlanRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::navfn::MakeNavPlanResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.plan_found);
    stream.next(m.error_message);
    stream.next(m.path);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MakeNavPlanResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<navfn::MakeNavPlan> {
  static const char* value() 
  {
    return "8ffef29bc8b086289124c16a8daa989d";
  }

  static const char* value(const navfn::MakeNavPlan&) { return value(); } 
};

template<>
struct DataType<navfn::MakeNavPlan> {
  static const char* value() 
  {
    return "navfn/MakeNavPlan";
  }

  static const char* value(const navfn::MakeNavPlan&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<navfn::MakeNavPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8ffef29bc8b086289124c16a8daa989d";
  }

  static const char* value(const navfn::MakeNavPlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<navfn::MakeNavPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "navfn/MakeNavPlan";
  }

  static const char* value(const navfn::MakeNavPlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<navfn::MakeNavPlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8ffef29bc8b086289124c16a8daa989d";
  }

  static const char* value(const navfn::MakeNavPlanResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<navfn::MakeNavPlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "navfn/MakeNavPlan";
  }

  static const char* value(const navfn::MakeNavPlanResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NAVFN_SERVICE_MAKENAVPLAN_H

