; Auto-generated. Do not edit!


(in-package move_base_msgs-msg)


;//! \htmlinclude MoveBaseResult.msg.html

(defclass <MoveBaseResult> (ros-message)
  ()
)
(defmethod serialize ((msg <MoveBaseResult>) ostream)
  "Serializes a message object of type '<MoveBaseResult>"
)
(defmethod deserialize ((msg <MoveBaseResult>) istream)
  "Deserializes a message object of type '<MoveBaseResult>"
  msg
)
(defmethod ros-datatype ((msg (eql '<MoveBaseResult>)))
  "Returns string type for a message object of type '<MoveBaseResult>"
  "move_base_msgs/MoveBaseResult")
(defmethod md5sum ((type (eql '<MoveBaseResult>)))
  "Returns md5sum for a message object of type '<MoveBaseResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(defmethod message-definition ((type (eql '<MoveBaseResult>)))
  "Returns full string definition for message of type '<MoveBaseResult>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(defmethod serialization-length ((msg <MoveBaseResult>))
  (+ 0
))
(defmethod ros-message-to-list ((msg <MoveBaseResult>))
  "Converts a ROS message object to a list"
  (list '<MoveBaseResult>
))
