; Auto-generated. Do not edit!


(in-package move_base_msgs-msg)


;//! \htmlinclude MoveBaseGoal.msg.html

(defclass <MoveBaseGoal> (ros-message)
  ((target_pose
    :reader target_pose-val
    :initarg :target_pose
    :type geometry_msgs-msg:<PoseStamped>
    :initform (make-instance 'geometry_msgs-msg:<PoseStamped>)))
)
(defmethod serialize ((msg <MoveBaseGoal>) ostream)
  "Serializes a message object of type '<MoveBaseGoal>"
  (serialize (slot-value msg 'target_pose) ostream)
)
(defmethod deserialize ((msg <MoveBaseGoal>) istream)
  "Deserializes a message object of type '<MoveBaseGoal>"
  (deserialize (slot-value msg 'target_pose) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<MoveBaseGoal>)))
  "Returns string type for a message object of type '<MoveBaseGoal>"
  "move_base_msgs/MoveBaseGoal")
(defmethod md5sum ((type (eql '<MoveBaseGoal>)))
  "Returns md5sum for a message object of type '<MoveBaseGoal>"
  "257d089627d7eb7136c24d3593d05a16")
(defmethod message-definition ((type (eql '<MoveBaseGoal>)))
  "Returns full string definition for message of type '<MoveBaseGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: roslib/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(defmethod serialization-length ((msg <MoveBaseGoal>))
  (+ 0
     (serialization-length (slot-value msg 'target_pose))
))
(defmethod ros-message-to-list ((msg <MoveBaseGoal>))
  "Converts a ROS message object to a list"
  (list '<MoveBaseGoal>
    (cons ':target_pose (target_pose-val msg))
))
