; Auto-generated. Do not edit!


(in-package move_base_msgs-msg)


;//! \htmlinclude MoveBaseFeedback.msg.html

(defclass <MoveBaseFeedback> (ros-message)
  ((base_position
    :reader base_position-val
    :initarg :base_position
    :type geometry_msgs-msg:<PoseStamped>
    :initform (make-instance 'geometry_msgs-msg:<PoseStamped>)))
)
(defmethod serialize ((msg <MoveBaseFeedback>) ostream)
  "Serializes a message object of type '<MoveBaseFeedback>"
  (serialize (slot-value msg 'base_position) ostream)
)
(defmethod deserialize ((msg <MoveBaseFeedback>) istream)
  "Deserializes a message object of type '<MoveBaseFeedback>"
  (deserialize (slot-value msg 'base_position) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<MoveBaseFeedback>)))
  "Returns string type for a message object of type '<MoveBaseFeedback>"
  "move_base_msgs/MoveBaseFeedback")
(defmethod md5sum ((type (eql '<MoveBaseFeedback>)))
  "Returns md5sum for a message object of type '<MoveBaseFeedback>"
  "3fb824c456a757373a226f6d08071bf0")
(defmethod message-definition ((type (eql '<MoveBaseFeedback>)))
  "Returns full string definition for message of type '<MoveBaseFeedback>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped base_position~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: roslib/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(defmethod serialization-length ((msg <MoveBaseFeedback>))
  (+ 0
     (serialization-length (slot-value msg 'base_position))
))
(defmethod ros-message-to-list ((msg <MoveBaseFeedback>))
  "Converts a ROS message object to a list"
  (list '<MoveBaseFeedback>
    (cons ':base_position (base_position-val msg))
))
