#goal definition
int32 command
int32 STOW_ARM = 0
int32 STORE_OBJECT = 1
---
#result definition
std_msgs/Header header
actionlib_msgs/GoalStatus status
arm_navigation_msgs/MoveArmResult result
---
#feedback
