#request constants
uint8 CLOSE=0
uint8 OPEN=1
uint8 CHECK=2
#request fields
int8 command
---
#response constants
uint8 CLOSED=0
uint8 OPEN=1
int8 SUCCESS=1
int8 FAILURE=-1
#response fields
uint8 position
int8 success
