/* auto-generated by genmsg_cpp from /opt/igvc_ros/harlie_base/msg/Pose.msg.  Do not edit! */
package ros.pkg.harlie_base.msg;


import java.nio.ByteBuffer;

public  class Pose extends ros.communication.Message
{

  public ros.pkg.roslib.msg.Header header;
  public float x;
  public float y;
  public float theta;
  public float x_var;
  public float y_var;
  public float theta_var;
  public float x_vel;
  public float y_vel;
  public float theta_vel;

  public Pose() {
 super();
    header = new ros.pkg.roslib.msg.Header();

  }
  public static java.lang.String __s_getDataType() { return "harlie_base/Pose"; }
  public static java.lang.String __s_getMD5Sum() { return "6912a6eb81006b68b259c9bf26039f96"; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "Header header\n" + 
    "float32 x\n" + 
    "float32 y\n" + 
    "float32 theta\n" + 
    "float32 x_var\n" + 
    "float32 y_var\n" + 
    "float32 theta_var\n" + 
    "float32 x_vel\n" + 
    "float32 y_vel\n" + 
    "float32 theta_vel\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: roslib/Header\n" + 
    "# Standard metadata for higher-level stamped data types.\n" + 
    "# This is generally used to communicate timestamped data \n" + 
    "# in a particular coordinate frame.\n" + 
    "# \n" + 
    "# sequence ID: consecutively increasing ID \n" + 
    "uint32 seq\n" + 
    "#Two-integer timestamp that is expressed as:\n" + 
    "# * stamp.secs: seconds (stamp_secs) since epoch\n" + 
    "# * stamp.nsecs: nanoseconds since stamp_secs\n" + 
    "# time-handling sugar is provided by the client library\n" + 
    "time stamp\n" + 
    "#Frame this data is associated with\n" + 
    "# 0: no frame\n" + 
    "# 1: global frame\n" + 
    "string frame_id\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public Pose clone() {
    Pose clone = (Pose)super.clone();
      header = (ros.pkg.roslib.msg.Header)header.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("header", "ros.pkg.roslib.msg.Header");
     m.put("x", "float");
     m.put("y", "float");
     m.put("theta", "float");
     m.put("x_var", "float");
     m.put("y_var", "float");
     m.put("theta_var", "float");
     m.put("x_vel", "float");
     m.put("y_vel", "float");
     m.put("theta_vel", "float");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.roslib.msg.Header");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Pose)) throw new RuntimeException("Invalid Type");
    Pose __m2 = (Pose) __m;
    header = __m2.header;
    x = __m2.x;
    y = __m2.y;
    theta = __m2.theta;
    x_var = __m2.x_var;
    y_var = __m2.y_var;
    theta_var = __m2.theta_var;
    x_vel = __m2.x_vel;
    y_vel = __m2.y_vel;
    theta_vel = __m2.theta_vel;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += header.serializationLength(); // header
    __l += 4; // x
    __l += 4; // y
    __l += 4; // theta
    __l += 4; // x_var
    __l += 4; // y_var
    __l += 4; // theta_var
    __l += 4; // x_vel
    __l += 4; // y_vel
    __l += 4; // theta_vel
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    ros.pkg.roslib.msg.Header _ser_header = header;
    boolean __reset_seq = (header.seq == 0);
    if (__reset_seq) _ser_header.seq = seq;
    boolean __reset_timestamp = header.stamp.isZero();
    if (__reset_timestamp)
      _ser_header.stamp = ros.Ros.getInstance().now();
     header.serialize(bb, seq);
    bb.putFloat(x);
    bb.putFloat(y);
    bb.putFloat(theta);
    bb.putFloat(x_var);
    bb.putFloat(y_var);
    bb.putFloat(theta_var);
    bb.putFloat(x_vel);
    bb.putFloat(y_vel);
    bb.putFloat(theta_vel);
  }
  public void deserialize(ByteBuffer bb)  {
     header.deserialize(bb);
    x = bb.getFloat();
    y = bb.getFloat();
    theta = bb.getFloat();
    x_var = bb.getFloat();
    y_var = bb.getFloat();
    theta_var = bb.getFloat();
    x_vel = bb.getFloat();
    y_vel = bb.getFloat();
    theta_vel = bb.getFloat();
  }
}

