/* auto-generated by genmsg_cpp from /opt/igvc_ros/harlie_base/msg/Sonar.msg.  Do not edit! */
package ros.pkg.harlie_base.msg;


import java.nio.ByteBuffer;

public  class Sonar extends ros.communication.Message
{

  public ros.pkg.roslib.msg.Header header;
  public float dist;

  public Sonar() {
 super();
    header = new ros.pkg.roslib.msg.Header();

  }
  public static java.lang.String __s_getDataType() { return "harlie_base/Sonar"; }
  public static java.lang.String __s_getMD5Sum() { return "32a7fd24a5630b5643e0d1882893197a"; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "Header header\n" + 
    "float32 dist\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: roslib/Header\n" + 
    "# Standard metadata for higher-level stamped data types.\n" + 
    "# This is generally used to communicate timestamped data \n" + 
    "# in a particular coordinate frame.\n" + 
    "# \n" + 
    "# sequence ID: consecutively increasing ID \n" + 
    "uint32 seq\n" + 
    "#Two-integer timestamp that is expressed as:\n" + 
    "# * stamp.secs: seconds (stamp_secs) since epoch\n" + 
    "# * stamp.nsecs: nanoseconds since stamp_secs\n" + 
    "# time-handling sugar is provided by the client library\n" + 
    "time stamp\n" + 
    "#Frame this data is associated with\n" + 
    "# 0: no frame\n" + 
    "# 1: global frame\n" + 
    "string frame_id\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public Sonar clone() {
    Sonar clone = (Sonar)super.clone();
      header = (ros.pkg.roslib.msg.Header)header.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("header", "ros.pkg.roslib.msg.Header");
     m.put("dist", "float");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.roslib.msg.Header");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Sonar)) throw new RuntimeException("Invalid Type");
    Sonar __m2 = (Sonar) __m;
    header = __m2.header;
    dist = __m2.dist;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += header.serializationLength(); // header
    __l += 4; // dist
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    ros.pkg.roslib.msg.Header _ser_header = header;
    boolean __reset_seq = (header.seq == 0);
    if (__reset_seq) _ser_header.seq = seq;
    boolean __reset_timestamp = header.stamp.isZero();
    if (__reset_timestamp)
      _ser_header.stamp = ros.Ros.getInstance().now();
     header.serialize(bb, seq);
    bb.putFloat(dist);
  }
  public void deserialize(ByteBuffer bb)  {
     header.deserialize(bb);
    dist = bb.getFloat();
  }
}

